name: ua-contract
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - r-base=4.5.3
  - r-seurat=5.5.1
  - r-arrow=25
  - r-matrix
  - r-jsonlite
  - r-digest
  - r-data.table
  - r-dplyr
  - r-qs
  - r-qs2
  - r-harmony
  - r-tidyverse
  - r-tictoc
  - r-pheatmap
  - r-dbscan
