"""時刻まわりの 2 つの欠陥に対する番人（ver56.3）。

■ 1. コンテナが UTC のまま動いていた

`docker-compose.yml` にも `Dockerfile` にも TZ 指定が無く、コンテナは UTC で
動いていた。日本時間 17:23 に開始した解析が「08:23開始」と表示され、
出力フォルダ名・ログ・projects.json の更新日時も全部 9 時間ずれていた。

インフラ側の設定なので pytest では実挙動を再現できない。代わりに
**設定が消えていないこと**を静的に照合する（消したら気づけないため）。

■ 2. 出力フォルダー名がアプリ起動時刻で固定されていた

`app.layout = create_main_layout()` は import 時に 1 度だけ評価されるので、
`settings_tab.py` の `datetime.now().strftime("Analysis_%Y%m%d_%H%M%S")` は
**起動した瞬間の時刻**で焼き付く。何時間経っても同じ名前が出るため、そのまま
実行すると前回と同じフォルダを指し、毎回上書き確認に当たる。
"""

import re
from pathlib import Path

import pytest
from dash import no_update

REPO = Path(__file__).resolve().parent.parent.parent


# ---------------------------------------------------------------------------
# 1. タイムゾーン設定が消えていないこと
# ---------------------------------------------------------------------------

class TestTimezoneIsConfigured:

    def test_compose_passes_tz_to_the_container(self):
        text = (REPO / "docker-compose.yml").read_text(encoding="utf-8")
        assert re.search(r"^\s*-\s*TZ=", text, re.MULTILINE), (
            "docker-compose.yml が TZ をコンテナに渡していない。"
            "外すとコンテナは UTC に戻り、表示時刻が 9 時間ずれる"
        )

    def test_compose_default_is_tokyo(self):
        text = (REPO / "docker-compose.yml").read_text(encoding="utf-8")
        assert "TZ=${TZ:-Asia/Tokyo}" in text, (
            ".env で上書きできる形（${TZ:-Asia/Tokyo}）で渡すこと"
        )

    def test_image_has_tzdata_and_a_default_zone(self):
        """TZ 環境変数だけ渡しても zoneinfo が無ければ UTC のままになる。"""
        text = (REPO / "Dockerfile").read_text(encoding="utf-8")
        assert "tzdata" in text, "Dockerfile が tzdata を入れていない"
        assert re.search(r"^ENV TZ=", text, re.MULTILINE), (
            "Dockerfile に既定 TZ が無い。compose を経由せず docker run した"
            "ときに UTC へ落ちる"
        )


# ---------------------------------------------------------------------------
# 2. 出力フォルダー名が「今」で作り直されること
# ---------------------------------------------------------------------------

class TestOutputSubfolderIsRefreshed:

    @staticmethod
    def _call(active_tab, current):
        from app.callbacks.analysis_callbacks import refresh_output_subfolder
        return refresh_output_subfolder(active_tab, current)

    def test_stale_autogenerated_name_is_replaced(self):
        """★ 本丸: 起動時刻で固まった名前を今の時刻に差し替える。"""
        stale = "Analysis_20260813_074823"
        got = self._call("settings", stale)
        assert got != stale
        assert re.match(r"^Analysis_\d{8}_\d{6}$", got), got

    def test_empty_value_is_filled(self):
        got = self._call("settings", "")
        assert re.match(r"^Analysis_\d{8}_\d{6}$", got), got

    @pytest.mark.parametrize("name", [
        "260813_Clinical_HCC",
        "Analysis_final",
        "Analysis_20260813",            # 桁が足りない = 手で書いた
        "Analysis_20260813_074823_v2",
    ])
    def test_user_named_folders_are_left_alone(self, name):
        """★ 利用者が付け直した名前を消さない。"""
        assert self._call("settings", name) is no_update

    @pytest.mark.parametrize("tab", ["interactive", "hne", None])
    def test_other_tabs_do_not_touch_it(self, tab):
        assert self._call(tab, "Analysis_20260813_074823") is no_update
